server:
  servlet:
    context-path: /elon-rpc-proxy
  port: 10002
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 20480

  ssl:
    key-store: keystore.p12
    key-store-password: elon123
    keyStoreType: PKCS12
    keyAlias: springboothttps